"""
scripts/generate_dimension_seed.py

One-shot generator: replaces the synthetic `muni` and `classification_code`
seed blocks in supabase/seed.sql with real dimension data --

  - classification_code: the full 672-code MOI codebook tree, read from
    pipeline/analysis/moi_budget_codes.json (produced by
    scripts/parse_codebook.py).
  - muni: the real Israeli municipality list, read from
    data/localities/municipalities.json (produced by
    src/muni_budget_analysis/scrapers/localities.py -- run that scraper
    first if this file doesn't exist yet).

The 3 synthetic muni rows (901-903) that the existing budget/budget_line_item
seed rows reference are kept, appended verbatim after the real rows in the
same insert statement -- see supabase/seed.sql's header comment.

muni_id collision note: city/local-council muni_key is keyed by CBS
locality_code, regional-council muni_key is keyed by CBS status_code, and
those two integer spaces collide (6 known collisions as of this writing:
26, 28, 29, 31, 41, 65). Regional-council muni_id is stored as the negated
status_code (muni_id = -municipality_code) to resolve this; cities/local
councils keep their positive code. check_collisions() re-verifies this holds
for whatever data.gov.il returns on a given run rather than trusting the
count above, and aborts loudly if it doesn't.

Usage:
    python scripts/generate_dimension_seed.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSIFICATION_CODES_PATH = REPO_ROOT / "pipeline" / "analysis" / "moi_budget_codes.json"
MUNICIPALITIES_PATH = REPO_ROOT / "data" / "localities" / "municipalities.json"
BUDGET_FILES_CSV_PATH = REPO_ROOT / "data" / "budgets" / "budget_files.csv"
SEED_SQL_PATH = REPO_ROOT / "supabase" / "seed.sql"

EXPECTED_CLASSIFICATION_CODE_COUNT = 672

SIDE_TO_CATEGORY = {"receipts": "income", "payments": "expense"}

REGIONAL_COUNCIL_TYPE = "מועצה אזורית"
UNASSIGNED_TYPE = "חסר מעמד מוניציפלי"
NAME_EN_ELIGIBLE_TYPES = {"עירייה", "מועצה מקומית"}

# The 3 synthetic muni rows the existing budget/budget_line_item seed rows
# reference -- kept byte-identical to supabase/seed.sql as it stood before
# this script's first run, appended after the real rows.
SYNTHETIC_MUNI_ROWS = [
    "    (901, 'כפר הדוגמה', 'Kfar HaDugma (sample)', 'local council', 'מרכז', 5, 12000)",
    "    (902, 'עיריית מבחן', 'Mivchan City (sample)', 'city', 'צפון', 7, 85000)",
    "    (903, 'המועצה האזורית לדוגמה', 'Example Regional Council', 'regional council', 'דרום', 4, 25000)",
]
SYNTHETIC_MUNI_IDS = {901, 902, 903}

SEED_HEADER = """-- Mock/fixture data for dev tables. Applied live to the dev project via
-- the REST API (see PR description); this file makes the same data
-- reviewable and reproducible (e.g. via `supabase db reset` locally).
-- classification_code holds the full 672-code MOI codebook tree
-- (pipeline/analysis/moi_budget_codes.json, parsed from the source PDF by
-- scripts/parse_codebook.py). muni holds the real Israeli municipality list
-- (data/localities/municipalities.json, from
-- src/muni_budget_analysis/scrapers/localities.py) plus 3 synthetic rows
-- (901-903) retained because the synthetic budget/budget_line_item rows
-- below reference them. Regional-council muni_id values are negated CBS
-- status_codes (muni_id = -municipality_code): status_code and locality_code
-- share the same integer space and collide for several regional councils
-- (e.g. code 26/28/29/31/41/65 also naming a city or local council);
-- negation keeps every muni_id unique without renumbering anything. Both
-- blocks are generated by scripts/generate_dimension_seed.py -- do not
-- hand-edit, re-run the generator instead.
"""


def sql_str(value: str) -> str:
    """Quote a SQL string literal, escaping embedded single quotes ('->'')."""
    return "'" + value.replace("'", "''") + "'"


def sql_str_or_null(value: str | None) -> str:
    return "null" if value is None else sql_str(value)


def sql_num_or_null(value) -> str:
    return "null" if value is None else str(value)


# --- classification_code ----------------------------------------------------


def load_classification_codes() -> list[dict]:
    entries = json.loads(CLASSIFICATION_CODES_PATH.read_text(encoding="utf-8"))
    rows = [
        {
            "code": e["code"],
            "parent_code": e["parent"],
            "level": e["level"],
            "category": SIDE_TO_CATEGORY[e["side"]],
            "standard_label_he": e["label"],
        }
        for e in entries
    ]
    rows.sort(key=lambda r: (r["level"], r["code"]))

    if len(rows) != EXPECTED_CLASSIFICATION_CODE_COUNT:
        raise SystemExit(
            f"Expected {EXPECTED_CLASSIFICATION_CODE_COUNT} classification codes, "
            f"got {len(rows)} from {CLASSIFICATION_CODES_PATH}"
        )
    return rows


def render_classification_code_sql(rows: list[dict]) -> str:
    lines = [
        "    ({code}, {parent_code}, {level}, {category}, {label})".format(
            code=sql_str(r["code"]),
            parent_code=sql_str_or_null(r["parent_code"]),
            level=r["level"],
            category=sql_str(r["category"]),
            label=sql_str(r["standard_label_he"]),
        )
        for r in rows
    ]
    return (
        "-- classification_code (parent-before-child)\n"
        "insert into classification_code (code, parent_code, level, category, standard_label_he) values\n"
        + ",\n".join(lines)
        + ";\n"
    )


# --- muni --------------------------------------------------------------------


def parse_cluster(raw: str, unparseable_seen: set[str]) -> int | None:
    raw = (raw or "").strip()
    if not raw:
        return None
    try:
        value = int(raw)
    except ValueError:
        unparseable_seen.add(raw)
        return None
    if 1 <= value <= 10:
        return value
    unparseable_seen.add(raw)
    return None


def load_municipalities() -> list[dict]:
    municipalities = json.loads(MUNICIPALITIES_PATH.read_text(encoding="utf-8"))

    unparseable_clusters: set[str] = set()
    rows: list[dict] = []

    for m in municipalities:
        authority_type = m["municipality_type"]
        original_code = m["municipality_code"]

        if authority_type == UNASSIGNED_TYPE:
            print(
                f"Excluding unassigned bucket (municipality_code=0): "
                f"{m['num_localities']} localities, population {m['total_population']}"
            )
            continue

        muni_id = -original_code if authority_type == REGIONAL_COUNCIL_TYPE else original_code

        name_en = None
        if authority_type in NAME_EN_ELIGIBLE_TYPES:
            for loc in m.get("localities", []):
                if loc.get("locality_code") == original_code:
                    candidate = (loc.get("locality_name_en") or "").strip()
                    if candidate:
                        name_en = candidate
                    break

        rows.append(
            {
                "muni_id": muni_id,
                "original_code": original_code,
                "name_he": m["municipality_name"],
                "name_en": name_en,
                "authority_type": authority_type,
                "district": m.get("district_name") or None,
                "socioeconomic_cluster": parse_cluster(m.get("cluster", ""), unparseable_clusters),
                "population": m.get("total_population"),
            }
        )

    if unparseable_clusters:
        print(f"Unparseable cluster values seen (set to null): {sorted(unparseable_clusters)}")

    return rows


def check_collisions(rows: list[dict]) -> None:
    by_id: dict[int, list[dict]] = {}
    for r in rows:
        by_id.setdefault(r["muni_id"], []).append(r)

    duplicates = {muni_id: group for muni_id, group in by_id.items() if len(group) > 1}
    if duplicates:
        print("FATAL: muni_id collisions found after negation fix:")
        for muni_id, group in duplicates.items():
            print(f"  muni_id={muni_id}:")
            for r in group:
                print(f"    original_code={r['original_code']} type={r['authority_type']} name={r['name_he']}")
        raise SystemExit(1)

    real_ids = set(by_id)
    overlap = real_ids & SYNTHETIC_MUNI_IDS
    if overlap:
        print(f"FATAL: real muni_id values collide with synthetic ids 901/902/903: {sorted(overlap)}")
        raise SystemExit(1)


def cross_check_budget_files(rows: list[dict]) -> None:
    if not BUDGET_FILES_CSV_PATH.exists():
        print(f"Cross-check skipped: {BUDGET_FILES_CSV_PATH} not found")
        return

    with BUDGET_FILES_CSV_PATH.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        budget_codes = {
            int(row["municipality_code"])
            for row in reader
            if row.get("municipality_code") not in (None, "")
        }

    generated_codes = {r["original_code"] for r in rows}
    missing = sorted(budget_codes - generated_codes)
    if missing:
        print(
            f"WARNING: {len(missing)} municipality_code value(s) in "
            f"{BUDGET_FILES_CSV_PATH} not found in generated muni list: {missing}"
        )
    else:
        print(f"Cross-check ok: all {len(budget_codes)} budget_files.csv municipality codes accounted for")


def render_muni_sql(rows: list[dict]) -> str:
    real_sorted = sorted(rows, key=lambda r: (r["authority_type"], r["name_he"]))
    lines = [
        "    ({muni_id}, {name_he}, {name_en}, {authority_type}, {district}, {cluster}, {population})".format(
            muni_id=r["muni_id"],
            name_he=sql_str(r["name_he"]),
            name_en=sql_str_or_null(r["name_en"]),
            authority_type=sql_str(r["authority_type"]),
            district=sql_str_or_null(r["district"]),
            cluster=sql_num_or_null(r["socioeconomic_cluster"]),
            population=sql_num_or_null(r["population"]),
        )
        for r in real_sorted
    ]
    lines.extend(SYNTHETIC_MUNI_ROWS)

    return (
        "-- muni\n"
        "insert into muni (muni_id, name_he, name_en, authority_type, district, socioeconomic_cluster, population) values\n"
        + ",\n".join(lines)
        + ";\n"
    )


# --- splice into supabase/seed.sql -------------------------------------------


def splice_seed_sql(muni_sql: str, classification_code_sql: str) -> None:
    """Replace the header comment + muni + classification_code blocks in
    supabase/seed.sql, leaving the budget/budget_line_item blocks (from the
    "-- budget" marker onward) completely untouched.
    """
    text = SEED_SQL_PATH.read_text(encoding="utf-8")

    muni_marker = "-- muni\n"
    budget_marker = "-- budget\n"

    if muni_marker not in text:
        raise SystemExit(f"Could not find {muni_marker!r} marker in {SEED_SQL_PATH} -- aborting splice")

    budget_start = text.index(budget_marker)

    untouched_tail = text[budget_start:]

    new_text = (
        SEED_HEADER
        + "\n"
        + muni_sql
        + "\n"
        + classification_code_sql
        + "\n"
        + untouched_tail
    )

    SEED_SQL_PATH.write_text(new_text, encoding="utf-8")

    # sanity: confirm the budget/budget_line_item tail is byte-identical
    rewritten = SEED_SQL_PATH.read_text(encoding="utf-8")
    if not rewritten.endswith(untouched_tail):
        raise SystemExit("budget/budget_line_item blocks were altered by splice -- aborting")


def main() -> None:
    classification_rows = load_classification_codes()
    muni_rows = load_municipalities()

    check_collisions(muni_rows)
    cross_check_budget_files(muni_rows)

    muni_sql = render_muni_sql(muni_rows)
    classification_code_sql = render_classification_code_sql(classification_rows)

    splice_seed_sql(muni_sql, classification_code_sql)

    print()
    print("=== Summary ===")
    print(f"classification_code rows: {len(classification_rows)}")
    print(f"muni rows: {len(muni_rows) + len(SYNTHETIC_MUNI_ROWS)} "
          f"({len(muni_rows)} real + {len(SYNTHETIC_MUNI_ROWS)} synthetic)")
    print(f"Written to {SEED_SQL_PATH}")


if __name__ == "__main__":
    main()
