"""
scripts/generate_budget_code_suffix_seed.py

One-shot generator: reads pipeline/analysis/moi_budget_code_suffixes.json
(produced by scripts/parse_codebook.py's parse_suffix_codebook()) and writes
a single `insert into budget_code_suffix (...) values (...), ...;` statement
to supabase/migrations/20260730233423_seed_budget_code_suffix.sql, seeding
the full 163-row suffix-code catalog (see
supabase/migrations/20260730233420_create_budget_code_suffix.sql for the
table this seeds).

Rows are ordered by (side, level, suffix_code) for readability, not the
source JSON's (side, suffix_code) order.

Usage:
    python scripts/generate_budget_code_suffix_seed.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INPUT_PATH = REPO_ROOT / "pipeline" / "analysis" / "moi_budget_code_suffixes.json"
OUTPUT_PATH = REPO_ROOT / "supabase" / "migrations" / "20260730233423_seed_budget_code_suffix.sql"


def sql_str(value: str) -> str:
    """Quote a SQL string literal, escaping embedded single quotes ('->'')."""
    return "'" + value.replace("'", "''") + "'"


def sql_str_or_null(value: str | None) -> str:
    return "null" if value is None else sql_str(value)


def format_row(entry: dict) -> str:
    return "    ({side}, {suffix_code}, {parent}, {level}, {label}, {source_page})".format(
        side=sql_str(entry["side"]),
        suffix_code=sql_str(entry["suffix_code"]),
        parent=sql_str_or_null(entry["parent"]),
        level=entry["level"],
        label=sql_str(entry["label"]),
        source_page=entry["source_page"],
    )


def main() -> None:
    entries = json.loads(INPUT_PATH.read_text(encoding="utf-8"))
    entries = sorted(entries, key=lambda e: (e["side"], e["level"], e["suffix_code"]))

    header = (
        "-- Seed data for budget_code_suffix: full 163-row suffix-code catalog, generated by\n"
        "-- scripts/generate_budget_code_suffix_seed.py from\n"
        "-- pipeline/analysis/moi_budget_code_suffixes.json. Do not hand-edit -- re-run the\n"
        "-- generator instead.\n"
    )
    rows_sql = ",\n".join(format_row(e) for e in entries)
    statement = (
        f"{header}\n"
        "insert into budget_code_suffix (side, suffix_code, parent_suffix_code, level, label_he, source_page) values\n"
        f"{rows_sql};\n"
    )

    OUTPUT_PATH.write_text(statement, encoding="utf-8")
    print(f"Wrote {len(entries)} rows to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
