-- Backfill muni.authority_type/district/socioeconomic_cluster/population,
-- fields docs/handshake-level3-postgres.md flags as not yet populated.
-- Source: the MOI/CBS regional-clustering register sheet
-- (data/localities/moi_socioeconomic_register_2024.csv) -- note this list
-- covers 174 of the 253 live munis (it's a regional-clustering membership
-- list, not a full municipality register -- several large self-sufficient
-- cities and a handful of local councils are legitimately absent, not
-- missed matches). Matched rows get real values; the other 79 unmatched
-- live rows get authority_type='unknown' in place of the previous
-- 'רשויות מקומיות' placeholder (name_he-only from
-- 20260731010123_seed_muni_semel_yeshuv.sql) rather than leaving a
-- misleading value in place. See
-- data/localities/moi_socioeconomic_register_2024_match_review.csv for
-- the full sheet-row <-> muni_id mapping, including the 3 sheet rows with
-- no live match (נווה מדבר, שער השומרון, תפן). Idempotent.

update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 1026;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 8, population = 22100 where muni_id = 1350;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 1351;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 8, population = 15389 where muni_id = 1352;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 1357;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 20169 where muni_id = 2101;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 5, population = 16823 where muni_id = 2102;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 8566 where muni_id = 2155;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 13329 where muni_id = 2203;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 15063 where muni_id = 2206;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 6, population = 15689 where muni_id = 2307;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 5, population = 34271 where muni_id = 2308;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 8, population = 40752 where muni_id = 2309;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 12510 where muni_id = 2313;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 31422 where muni_id = 2404;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 30768 where muni_id = 2456;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 6, population = 21270 where muni_id = 2971;
update muni set authority_type = 'regional council', district = 'חיפה', socioeconomic_cluster = 5, population = 13514 where muni_id = 3112;
update muni set authority_type = 'regional council', district = 'חיפה', socioeconomic_cluster = 7, population = 22185 where muni_id = 3214;
update muni set authority_type = 'regional council', district = 'חיפה', socioeconomic_cluster = 8, population = 35258 where muni_id = 3215;
update muni set authority_type = 'regional council', district = 'חיפה', socioeconomic_cluster = 8, population = 2041 where muni_id = 3245;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4116;
update muni set authority_type = 'regional council', district = 'מרכז', socioeconomic_cluster = 8, population = 22736 where muni_id = 4118;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4119;
update muni set authority_type = 'regional council', district = 'מרכז', socioeconomic_cluster = 8, population = 33644 where muni_id = 4220;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4225;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4330;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4340;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4427;
update muni set authority_type = 'regional council', district = 'מרכז', socioeconomic_cluster = 8, population = 8009 where muni_id = 4428;
update muni set authority_type = 'regional council', district = 'מרכז', socioeconomic_cluster = 6, population = 6572 where muni_id = 4429;
update muni set authority_type = 'regional council', district = 'מרכז', socioeconomic_cluster = 5, population = 10278 where muni_id = 4431;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 4432;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 7, population = 22726 where muni_id = 6133;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 6134;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 8, population = 9077 where muni_id = 6135;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 7, population = 19981 where muni_id = 6136;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 7, population = 9751 where muni_id = 6137;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 6150;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 6, population = 15754 where muni_id = 6238;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 6, population = 11480 where muni_id = 6239;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 7, population = 11662 where muni_id = 6241;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 6, population = 14953 where muni_id = 6242;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 6, population = 8467 where muni_id = 6248;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 6251;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 7, population = 11955 where muni_id = 6252;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 5, population = 5113 where muni_id = 6253;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 7, population = 4227 where muni_id = 6254;
update muni set authority_type = 'regional council', district = 'דרום', socioeconomic_cluster = 1, population = 20566 where muni_id = 6269;
update muni set authority_type = 'regional council', district = 'יהודה ושומרון', socioeconomic_cluster = 6, population = 48170 where muni_id = 7372;
update muni set authority_type = 'regional council', district = 'יהודה ושומרון', socioeconomic_cluster = 5, population = 80020 where muni_id = 7473;
update muni set authority_type = 'regional council', district = 'יהודה ושומרון', socioeconomic_cluster = 7, population = 2619 where muni_id = 7574;
update muni set authority_type = 'regional council', district = 'יהודה ושומרון', socioeconomic_cluster = 6, population = 7264 where muni_id = 7575;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 7676;
update muni set authority_type = 'regional council', district = 'יהודה ושומרון', socioeconomic_cluster = 5, population = 11827 where muni_id = 7778;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 13000;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 14000;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 15000;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 18600;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26100;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26200;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26300;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26400;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26500;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 26600;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 8, population = 97916 where muni_id = 26900;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 27400;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 28300;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 28400;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 6, population = 67477 where muni_id = 29100;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 30070;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 5, population = 46191 where muni_id = 31061;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 4, population = 39445 where muni_id = 32200;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 32600;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 32630;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 5, population = 24868 where muni_id = 32800;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 2, population = 51388 where muni_id = 36700;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 6, population = 61925 where muni_id = 36800;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 37000;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 37100;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 3, population = 76542 where muni_id = 37300;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 4, population = 52911 where muni_id = 37600;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 5, population = 65592 where muni_id = 37700;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 2, population = 38995 where muni_id = 38000;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 7, population = 50722 where muni_id = 38200;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 38500;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 3, population = 43640 where muni_id = 38800;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 39000;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 6, population = 46168 where muni_id = 39500;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 5, population = 41487 where muni_id = 39600;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 40565;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 40681;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 8, population = 18862 where muni_id = 42300;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 7, population = 22336 where muni_id = 42500;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 42620;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 42650;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 47200;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 8, population = 82014 where muni_id = 48700;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 3, population = 39388 where muni_id = 50031;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 3, population = 5659 where muni_id = 50099;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 50229;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 3, population = 54828 where muni_id = 50246;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 50466;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 5, population = 11079 where muni_id = 50469;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 6, population = 8258 where muni_id = 50812;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 4, population = 11942 where muni_id = 50831;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 4, population = 28465 where muni_id = 50874;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 2, population = 15001 where muni_id = 50922;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 51015;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 51020;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 5, population = 36284 where muni_id = 51031;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 3, population = 27176 where muni_id = 51034;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 5, population = 23097 where muni_id = 51063;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 5, population = 48019 where muni_id = 51139;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 10939 where muni_id = 52034;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 6, population = 32295 where muni_id = 52100;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 52400;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 3, population = 29579 where muni_id = 52560;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 52610;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 52640;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 52660;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 2, population = 5620 where muni_id = 53660;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 53780;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 4, population = 20158 where muni_id = 59200;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 60041;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 9, population = 14708 where muni_id = 60154;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 60166;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 7, population = 29494 where muni_id = 60168;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 60182;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 7, population = 24967 where muni_id = 60240;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 62530;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 7, population = 30566 where muni_id = 62550;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 7, population = 46032 where muni_id = 67800;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 8, population = 24078 where muni_id = 69300;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 9, population = 65125 where muni_id = 69700;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 2108 where muni_id = 70043;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 70267;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 70587;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 70666;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 5, population = 6465 where muni_id = 71066;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 9, population = 9143 where muni_id = 71224;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 9, population = 11617 where muni_id = 71268;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 71271;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 8, population = 8033 where muni_id = 73750;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 3205 where muni_id = 80026;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 8, population = 16317 where muni_id = 80028;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 1680 where muni_id = 80029;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 2, population = 4626 where muni_id = 80046;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 8, population = 4337 where muni_id = 80047;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 2091 where muni_id = 80065;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 8, population = 7957 where muni_id = 80122;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 80171;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 81137;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 81247;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 9, population = 5600 where muni_id = 81263;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 81304;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 81309;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 5, population = 4572 where muni_id = 83557;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 7, population = 4424 where muni_id = 83560;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 83570;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 4, population = 6424 where muni_id = 83574;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 83608;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 3, population = 7578 where muni_id = 83611;
update muni set authority_type = 'city', district = 'יהודה ושומרון', socioeconomic_cluster = 6, population = 36402 where muni_id = 83616;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 6, population = 10572 where muni_id = 83640;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 83650;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 83652;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 4, population = 24168 where muni_id = 83730;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 8, population = 9985 where muni_id = 83760;
update muni set authority_type = 'local council', district = 'יהודה ושומרון', socioeconomic_cluster = 9, population = 4274 where muni_id = 83769;
update muni set authority_type = 'city', district = 'יהודה ושומרון', socioeconomic_cluster = 1, population = 89787 where muni_id = 83797;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 8102 where muni_id = 84100;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90472;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 14489 where muni_id = 90473;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 15073 where muni_id = 90478;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 12394 where muni_id = 90480;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 3, population = 23418 where muni_id = 90481;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 10588 where muni_id = 90482;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 8689 where muni_id = 90483;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 6765 where muni_id = 90485;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 20225 where muni_id = 90486;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 3213 where muni_id = 90487;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 10755 where muni_id = 90489;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 12610 where muni_id = 90490;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90492;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 5, population = 18293 where muni_id = 90494;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 6786 where muni_id = 90496;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 14886 where muni_id = 90498;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 18862 where muni_id = 90499;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90500;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 16650 where muni_id = 90502;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 12525 where muni_id = 90504;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90505;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 9345 where muni_id = 90506;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 10559 where muni_id = 90507;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 6, population = 3477 where muni_id = 90508;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 25204 where muni_id = 90509;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90510;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 2, population = 9052 where muni_id = 90511;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 15316 where muni_id = 90516;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 3908 where muni_id = 90517;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 3227 where muni_id = 90518;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 8792 where muni_id = 90520;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 13983 where muni_id = 90522;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 4, population = 4286 where muni_id = 90525;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 13628 where muni_id = 90529;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 5798 where muni_id = 90530;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90531;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 14020 where muni_id = 90532;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 5, population = 13168 where muni_id = 90534;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 7, population = 3408 where muni_id = 90535;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 6093 where muni_id = 90536;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 3, population = 13484 where muni_id = 90537;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90538;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 2, population = 15805 where muni_id = 90541;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 17526 where muni_id = 90542;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 5, population = 8349 where muni_id = 90543;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 3, population = 10898 where muni_id = 90627;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90628;
update muni set authority_type = 'local council', district = 'מרכז', socioeconomic_cluster = 4, population = 3952 where muni_id = 90633;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 4, population = 26844 where muni_id = 90634;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 90637;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 3, population = 24799 where muni_id = 90638;
update muni set authority_type = 'local council', district = 'חיפה', socioeconomic_cluster = 5, population = 20927 where muni_id = 90654;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 6449 where muni_id = 90913;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 8265 where muni_id = 90944;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 7154 where muni_id = 90962;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 9101 where muni_id = 90975;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 6539 where muni_id = 90978;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 2, population = 11016 where muni_id = 90998;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 1, population = 24931 where muni_id = 91054;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 1, population = 20851 where muni_id = 91059;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 2, population = 18916 where muni_id = 91060;
update muni set authority_type = 'city', district = 'דרום', socioeconomic_cluster = 2, population = 78179 where muni_id = 91161;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 1, population = 21381 where muni_id = 91192;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 1, population = 15823 where muni_id = 91286;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 91290;
update muni set authority_type = 'local council', district = 'דרום', socioeconomic_cluster = 1, population = 22732 where muni_id = 91303;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 91326;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 91327;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 2, population = 9317 where muni_id = 92565;
update muni set authority_type = 'regional council', district = 'צפון', socioeconomic_cluster = 3, population = 8411 where muni_id = 92566;
update muni set authority_type = 'city', district = 'חיפה', socioeconomic_cluster = 2, population = 60194 where muni_id = 92710;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 5, population = 27495 where muni_id = 92720;
update muni set authority_type = 'city', district = 'מרכז', socioeconomic_cluster = 3, population = 46772 where muni_id = 92730;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 6931 where muni_id = 94001;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 11278 where muni_id = 94201;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 4178 where muni_id = 94203;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 2752 where muni_id = 94501;
update muni set authority_type = 'local council', district = 'צפון', socioeconomic_cluster = 3, population = 2443 where muni_id = 94502;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 96000;
update muni set authority_type = 'unknown', district = null, socioeconomic_cluster = null, population = null where muni_id = 97500;
update muni set authority_type = 'city', district = 'צפון', socioeconomic_cluster = 3, population = 36745 where muni_id = 98900;
